title: 寧靜居
description: 一個Minecraft伺服器的wiki
theme: just-the-docs

url: https://mcwiki.sfpdev.com

# Google Analytics Tracking (optional)
# Supports a CSV of tracking ID strings (eg. "UA-1234567-89,G-1AB234CDE5")
ga_tracking: G-V4F6MTCNTQ
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

# Aux links for the upper right navigation
aux_links:
  GitHub: https://github.com/cj0673/sfpdev-mcwiki

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Enable or disable the site search
# Supports true (default) or false
search_enabled: false

callouts:
  yellow:
    color: yellow

nav_external_links:
  - title: mc-list
    url: https://www.mc-list.xyz/2209/info
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false

  - title: 巴哈姆特
    url: https://forum.gamer.com.tw/C.php?bsn=18673&snA=202486&tnum=64&subbsn=18
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false
